export const SET_CURRENT_USER = Symbol('SET_CURRENT_USER')
export const GET_ALL_PRODUCTS = Symbol('GET_ALL_PRODUCTS')
export const GET_ALL_CATEGORIES = Symbol('GET_ALL_CATEGORIES')
export const ADD_TO_CART = Symbol('ADD_TO_CART')
export const GET_ALL_USER_ORDERS = Symbol('GET_ALL_USERS_ORDERS')
export const GET_ORDER_LINEITEMS = Symbol('GET_ORDER_LINEITEMS')
export const UPDATE_PRODUCT = Symbol('UPDATE_PRODUCT')
export const UPDATE_LINE_ITEM = Symbol('UPDATE_LINE_ITEM')
export const GET_ALL_REVIEWS = Symbol('GET_ALL_REVIEWS')
export const GET_ALL_USERS = Symbol('GET_ALL_USERS')
export const CREATE_ORDER = Symbol('CREATE_ORDER')
export const SET_USER_ORDERS = Symbol('SET_USER_ORDERS')
export const SET_USER_ORDERS_ON_LOGIN = Symbol('SET_USER_ORDERS_ON_LOGIN')

export const UPDATE_ORDER = Symbol('UPDATE_ORDER')
export const RESET_CART_TO_EMPTY = Symbol('RESET_CART_TO_EMPTY')
export const REMOVE_FROM_CART = Symbol('REMOVE_FROM_CART')
export const GET_USER_LINEITEMS = Symbol('GET_USER_LINEITEMS')
