export const LOGGED_IN_USER = Symbol('LOGGED_IN_USER')
export const GET_ALL_PRODUCTS = Symbol('GET_ALL_PRODUCTS')
export const ADD_TO_CART = Symbol('ADD_TO_CART')
export const GET_ALL_USER_ORDERS = Symbol('GET_ALL_USERS_ORDERS')
export const GET_ORDER_LINEITEMS = Symbol('GET_ORDER_LINEITEMS')
export const GET_ALL_REVIEWS = Symbol('GET_ALL_REVIEWS')
export const GET_ALL_USERS = Symbol('GET_ALL_USERS')
